// lang.rs — Internationalisation strings for VoidDream
//
// Supported languages:
//   en_gb  English (UK)       ro  Romanian        fr  French
//   de     German             es  Spanish          it  Italian
//   pt     Portuguese         ru  Russian          ja  Japanese
//   zh     Chinese            ko  Korean           ar  Arabic

/// All user-visible strings in one place.
/// Add new fields here when new UI text is introduced.
#[derive(Clone)]
#[allow(dead_code)]
pub struct Lang {
    // ── Settings section tabs ─────────────────────────────────────────────────
    pub sec_behaviour:  &'static str,
    pub sec_appearance: &'static str,
    pub sec_openers:    &'static str,
    pub sec_keybinds:   &'static str,
    pub sec_about:      &'static str,

    // ── Settings — Behaviour labels ───────────────────────────────────────────
    pub set_show_hidden:     &'static str,
    pub set_date_format:     &'static str,
    pub set_show_clock:      &'static str,
    pub set_show_mtime:      &'static str,

    // ── Settings — Keybind labels ─────────────────────────────────────────────
    pub kb_select:       &'static str,
    pub kb_select_all:   &'static str,
    pub kb_copy:         &'static str,
    pub kb_cut:          &'static str,
    pub kb_paste:        &'static str,
    pub kb_delete:       &'static str,
    pub kb_rename:       &'static str,
    pub kb_new_file:     &'static str,
    pub kb_new_dir:      &'static str,
    pub kb_search:       &'static str,
    pub kb_toggle_hidden:&'static str,
    pub kb_new_tab:      &'static str,
    pub kb_close_tab:    &'static str,
    pub kb_cycle_tab:    &'static str,
    pub kb_quit:         &'static str,
    pub kb_drives:       &'static str,
    pub kb_navigate:     &'static str,
    // Section headers for keybinds
    pub kb_header_nav:    &'static str,
    pub kb_header_sel:    &'static str,
    pub kb_header_ops:    &'static str,
    pub kb_header_tabs:   &'static str,
    pub kb_header_drives: &'static str,
    pub kb_header_app:    &'static str,
    // Nav key labels
    pub kb_nav_up:    &'static str,
    pub kb_nav_down:  &'static str,
    pub kb_nav_left:  &'static str,
    pub kb_nav_right: &'static str,
    pub kb_page_up:   &'static str,
    pub kb_page_down: &'static str,
    pub kb_first:     &'static str,
    pub kb_last:      &'static str,
    pub kb_open:         &'static str,
    pub kb_go_up:        &'static str,
    pub kb_jump:         &'static str,
    pub kb_first_last:   &'static str,
    pub kb_deselect_all: &'static str,
    pub kb_select_all2:  &'static str,
    pub kb_open_with:    &'static str,
    pub kb_settings:     &'static str,
    pub kb_help:         &'static str,
    pub kb_quit2:        &'static str,
    pub kb_drive_mount:  &'static str,
    pub kb_drive_unmount:&'static str,
    pub kb_drive_refresh:&'static str,
    pub kb_trash_open:   &'static str,
    // Keybind editor overlay
    pub kb_edit_add_one:    &'static str,
    pub kb_edit_add_combo:  &'static str,
    pub kb_edit_remove:     &'static str,
    pub kb_edit_reset:      &'static str,
    pub kb_edit_current:    &'static str,
    pub kb_edit_press_key:  &'static str,
    pub kb_edit_step1:      &'static str,
    pub kb_edit_step2:      &'static str,
    pub kb_edit_remove_title: &'static str,

    // ── Settings — About labels ───────────────────────────────────────────────
    pub about_app:       &'static str,
    pub about_ver:       &'static str,
    pub about_author:    &'static str,
    pub about_license:   &'static str,
    pub about_repo:      &'static str,
    pub about_tagline:   &'static str,
    pub about_built_with:&'static str,

    // ── Help overlay — section headers ────────────────────────────────────────
    pub help_navigation: &'static str,
    pub help_file_ops:   &'static str,
    pub help_search:     &'static str,
    pub help_tabs:       &'static str,
    pub help_app:        &'static str,

    // ── Help overlay — keybind descriptions ───────────────────────────────────
    pub help_move_cursor:    &'static str,
    pub help_open_enter:     &'static str,
    pub help_go_up:          &'static str,
    pub help_jump10:         &'static str,
    pub help_first_last:     &'static str,
    pub help_select:         &'static str,
    pub help_select_all:     &'static str,
    pub help_deselect_all:   &'static str,
    pub help_copy:           &'static str,
    pub help_cut:            &'static str,
    pub help_paste:          &'static str,
    pub help_delete:         &'static str,
    pub help_rename:         &'static str,
    pub help_new_file:       &'static str,
    pub help_new_dir:        &'static str,
    pub help_fuzzy:          &'static str,
    pub help_new_tab:        &'static str,
    pub help_close_tab:      &'static str,
    pub help_cycle_tab:      &'static str,
    pub help_toggle_hidden:  &'static str,
    pub help_drives:         &'static str,
    pub help_drive_mount:    &'static str,
    pub help_drive_unmount:  &'static str,
    pub help_drive_refresh:  &'static str,
    pub help_open_settings:  &'static str,
    pub help_show_help:      &'static str,
    pub help_quit:           &'static str,

    // ── Drive overlay ─────────────────────────────────────────────────────────
    pub drive_title:         &'static str,
    pub drive_no_devices:    &'static str,
    pub drive_tip_plug:      &'static str,
    pub drive_tip_mtp:       &'static str,
    pub drive_tip_jmtpfs:   &'static str,
    pub drive_col_name:      &'static str,
    pub drive_col_size:      &'static str,
    pub drive_col_fs:        &'static str,
    pub drive_col_mount:     &'static str,
    pub drive_hint_mount:    &'static str,
    pub drive_hint_unmount:  &'static str,
    pub drive_hint_navigate: &'static str,
    pub drive_hint_refresh:  &'static str,
    pub drive_hint_close:    &'static str,

    // ── Status messages ───────────────────────────────────────────────────────
    pub msg_already_mounted:    &'static str,
    pub msg_cant_close_tab:     &'static str,
    pub msg_cant_navigate:      &'static str,
    pub msg_not_mounted:        &'static str,
    pub msg_not_mounted_hint:   &'static str,
    pub msg_nothing_to_paste:   &'static str,
    pub msg_nothing_to_yank:    &'static str,
    pub msg_pasted:             &'static str,
    pub msg_select_first:       &'static str,
    pub msg_hidden_shown:       &'static str,
    pub msg_hidden_hidden:      &'static str,
    pub msg_copied:             &'static str,
    pub msg_cut:                &'static str,

    // ── Preview pane ─────────────────────────────────────────────────────────
    pub preview_folder_size:    &'static str,
    pub preview_items:          &'static str,
    pub preview_item:           &'static str,
    pub preview_computing:      &'static str,
    // ── Additional status / UI messages ──────────────────────────────────────
    pub msg_mounted_at:      &'static str,
    pub msg_mount_failed:    &'static str,
    pub msg_unmounted:       &'static str,
    pub msg_unmount_failed:  &'static str,
    pub msg_extracted:       &'static str,
    pub msg_extract_error:   &'static str,
    pub msg_deleted:         &'static str,
    pub msg_deleted_items:   &'static str,
    pub msg_error:           &'static str,
    pub msg_launching:       &'static str,
    pub msg_in_terminal:     &'static str,
    pub msg_tab_word:        &'static str,
    pub msg_opened_word:     &'static str,
    pub msg_settings_saved:  &'static str,
    pub msg_save_error:      &'static str,
    pub msg_unsaved_changes: &'static str,
    pub msg_extracting:      &'static str,
    pub msg_esc_cancel:      &'static str,
}

pub fn load(code: &str) -> &'static Lang {
    match code {
        "ro" | "Română"        => &RO,
        "fr" | "Français"      => &FR,
        "de" | "Deutsch"       => &DE,
        "es" | "Español"       => &ES,
        "it" | "Italiano"      => &IT,
        "pt" | "Português"     => &PT,
        "ru" | "Русский"       => &RU,
        "ja" | "日本語"          => &JA,
        "zh" | "中文"           => &ZH,
        "ko" | "한국어"          => &KO,
        "ar" | "العربية"       => &AR,
        _                      => &EN_GB,  // "en_gb", "English (UK)", or unknown
    }
}

// ── English (UK) ──────────────────────────────────────────────────────────────
static EN_GB: Lang = Lang {
    sec_behaviour: "Behaviour", sec_appearance: "Appearance",
    sec_openers: "Openers", sec_keybinds: "Keybinds", sec_about: "About",
    set_show_hidden: "Show hidden files", set_date_format: "Date format",
    set_show_clock: "Show clock in tab bar", set_show_mtime: "Show file date/time",
    kb_select: "Select / deselect", kb_select_all: "Select all",
    kb_copy: "Copy", kb_cut: "Cut", kb_paste: "Paste", kb_delete: "Delete",
    kb_rename: "Rename", kb_new_file: "New file", kb_new_dir: "New directory",
    kb_search: "Fuzzy search", kb_toggle_hidden: "Toggle hidden files",
    kb_new_tab: "New tab", kb_close_tab: "Close tab", kb_cycle_tab: "Cycle tabs",
    kb_quit: "Quit", kb_drives: "Drive / USB / phone manager",
    kb_header_nav: "── Navigation ──────────────────────────",
    kb_header_sel: "── Selection ───────────────────────────",
    kb_header_ops: "── File operations ─────────────────────",
    kb_header_tabs: "── Tabs ────────────────────────────────",
    kb_header_drives: "── Drives & Devices ────────────────────",
    kb_header_app: "── App ─────────────────────────────────",
    kb_nav_up: "Move up", kb_nav_down: "Move down",
    kb_nav_left: "Go up / back", kb_nav_right: "Open / enter",
    kb_page_up: "Jump up 10", kb_page_down: "Jump down 10",
    kb_first: "First entry", kb_last: "Last entry",
    kb_navigate: "Navigate", kb_open: "Open / enter dir", kb_go_up: "Go up",
    kb_jump: "Jump 10 entries", kb_first_last: "First / last entry",
    kb_deselect_all: "Deselect all", kb_select_all2: "Select all (alt)",
    kb_open_with: "Open with…", kb_settings: "Open settings",
    kb_help: "Show help", kb_quit2: "Quit (alt)",
    kb_drive_mount: "Mount selected device",
    kb_drive_unmount: "Unmount selected device",
    kb_drive_refresh: "Refresh device list",
    kb_trash_open: "Open trash browser",
    kb_edit_add_one: "Add one key binding",
    kb_edit_add_combo: "Add combination  (e.g. Ctrl+K)",
    kb_edit_remove: "Remove a binding",
    kb_edit_reset: "Reset to default",
    kb_edit_current: "Current",
    kb_edit_press_key: "Press any key — it will work on its own",
    kb_edit_step1: "Press the FIRST key of the combination",
    kb_edit_step2: "First key: {} — now press the SECOND key",
    kb_edit_remove_title: "Remove binding",
    about_app: "Application", about_ver: "Version", about_author: "Author",
    about_license: "Licence", about_repo: "Repository",
    about_tagline: "A dreamy void-themed TUI file manager",
    about_built_with: "Built with Rust + Ratatui",
    help_navigation: "Navigation", help_file_ops: "File Operations",
    help_search: "Search", help_tabs: "Tabs", help_app: "App",
    help_move_cursor: "Move cursor up / down",
    help_open_enter: "Open file or enter directory",
    help_go_up: "Go up to parent directory",
    help_jump10: "Jump 10 entries",
    help_first_last: "First / last entry",
    help_select: "Select / deselect file",
    help_select_all: "Select all",
    help_deselect_all: "Deselect all",
    help_copy: "Copy selected",
    help_cut: "Cut selected",
    help_paste: "Paste",
    help_delete: "Delete selected (with confirm)",
    help_rename: "Rename",
    help_new_file: "New file",
    help_new_dir: "New directory",
    help_fuzzy: "Fuzzy find (recursive search)",
    help_new_tab: "Open new tab",
    help_close_tab: "Close current tab",
    help_cycle_tab: "Cycle to next tab",
    help_toggle_hidden: "Toggle hidden files",
    help_drives: "Open drive / USB / phone manager",
    help_drive_mount: "Mount selected drive or phone",
    help_drive_unmount: "Unmount selected drive or phone",
    help_drive_refresh: "Refresh device list",
    help_open_settings: "Open settings",
    help_show_help: "Show this help",
    help_quit: "Quit",
    drive_title: "Drive Manager",
    drive_no_devices: "No removable drives or phones detected.",
    drive_tip_plug: "Plug in a USB drive or connect a phone via USB",
    drive_tip_mtp: "For Android phones: enable MTP mode on the phone",
    drive_tip_jmtpfs: "jmtpfs must be installed for phone support",
    drive_col_name: "Name", drive_col_size: "Size",
    drive_col_fs: "FS", drive_col_mount: "Mount point",
    drive_hint_mount: "mount", drive_hint_unmount: "unmount",
    drive_hint_navigate: "navigate", drive_hint_refresh: "refresh",
    drive_hint_close: "close",
    msg_already_mounted: "Already mounted — press u to unmount",
    msg_cant_close_tab: "Can't close last tab",
    msg_cant_navigate: "Cannot navigate into this partition type",
    msg_not_mounted: "Not mounted",
    msg_not_mounted_hint: "Not mounted — press m to mount first",
    msg_nothing_to_paste: "Nothing to paste",
    msg_nothing_to_yank: "Nothing to yank",
    msg_pasted: "Pasted successfully",
    msg_select_first: "Select files first (Space)",
    msg_hidden_shown: "Hidden files shown",
    msg_hidden_hidden: "Hidden files hidden",
    msg_copied: "copied", msg_cut: "cut",
    preview_folder_size: "Folder size", preview_items: "items",
    preview_item: "item", preview_computing: "…",
    msg_mounted_at: "Mounted at", msg_mount_failed: "Mount failed",
    msg_unmounted: "Unmounted", msg_unmount_failed: "Unmount failed",
    msg_extracted: "Extracted", msg_extract_error: "Extract error",
    msg_deleted: "Deleted", msg_deleted_items: "item(s)",
    msg_error: "Error", msg_launching: "Launching", msg_in_terminal: "in terminal",
    msg_tab_word: "Tab", msg_opened_word: "opened",
    msg_settings_saved: "Settings saved", msg_save_error: "Save error",
    msg_unsaved_changes: "Unsaved changes — press S to save",
    msg_extracting: "Extracting", msg_esc_cancel: "[Esc cancel]",
};

// ── Romanian ──────────────────────────────────────────────────────────────────
static RO: Lang = Lang {
    sec_behaviour: "Comportament", sec_appearance: "Aspect",
    sec_openers: "Deschizători", sec_keybinds: "Taste", sec_about: "Despre",
    set_show_hidden: "Arată fișierele ascunse", set_date_format: "Format dată",
    set_show_clock: "Afișează ceasul în bara de file",
    set_show_mtime: "Afișează data/ora fișierului",
    kb_select: "Selectează / deselectează", kb_select_all: "Selectează tot",
    kb_copy: "Copiază", kb_cut: "Decupează", kb_paste: "Lipește",
    kb_delete: "Șterge", kb_rename: "Redenumește",
    kb_new_file: "Fișier nou", kb_new_dir: "Director nou",
    kb_search: "Căutare fuzzy", kb_toggle_hidden: "Comută fișiere ascunse",
    kb_new_tab: "Tab nou", kb_close_tab: "Închide tab",
    kb_cycle_tab: "Rotire taburi", kb_quit: "Ieșire",
    kb_drives: "Manager unități / USB / telefon",
    kb_header_nav: "── Navigare ─────────────────────────────",
    kb_header_sel: "── Selecție ─────────────────────────────",
    kb_header_ops: "── Operații fișiere ─────────────────────",
    kb_header_tabs: "── Taburi ───────────────────────────────",
    kb_header_drives: "── Unități & Dispozitive ────────────────",
    kb_header_app: "── Aplicație ────────────────────────────",
    kb_nav_up: "Sus", kb_nav_down: "Jos",
    kb_nav_left: "Înapoi", kb_nav_right: "Deschide / intră",
    kb_page_up: "Salt 10 sus", kb_page_down: "Salt 10 jos",
    kb_first: "Prima intrare", kb_last: "Ultima intrare",
    kb_navigate: "Navigare", kb_open: "Deschide / intră în dir",
    kb_go_up: "Mergi sus", kb_jump: "Salt 10 intrări",
    kb_first_last: "Prima / ultima intrare",
    kb_deselect_all: "Deselectează tot", kb_select_all2: "Selectează tot (alt)",
    kb_open_with: "Deschide cu…", kb_settings: "Deschide setări",
    kb_help: "Afișează ajutor", kb_quit2: "Ieșire (alt)",
    kb_drive_mount: "Montează dispozitivul selectat",
    kb_drive_unmount: "Demontează dispozitivul selectat",
    kb_drive_refresh: "Reîmprospătează lista",
    kb_trash_open: "Deschide coșul de gunoi",
    kb_edit_add_one: "Adaugă o tastă",
    kb_edit_add_combo: "Adaugă combinație  (ex. Ctrl+K)",
    kb_edit_remove: "Elimină o asociere",
    kb_edit_reset: "Resetează implicit",
    kb_edit_current: "Curent",
    kb_edit_press_key: "Apasă orice tastă — va funcționa singură",
    kb_edit_step1: "Apasă PRIMA tastă a combinației",
    kb_edit_step2: "Prima tastă: {} — apasă acum A DOUA tastă",
    kb_edit_remove_title: "Elimină asocierea",
    about_app: "Aplicație", about_ver: "Versiune", about_author: "Autor",
    about_license: "Licență", about_repo: "Depozit",
    about_tagline: "Un manager de fișiere TUI cu temă void visătoare",
    about_built_with: "Construit cu Rust + Ratatui",
    help_navigation: "Navigare", help_file_ops: "Operații fișiere",
    help_search: "Căutare", help_tabs: "Taburi", help_app: "Aplicație",
    help_move_cursor: "Mișcă cursorul sus / jos",
    help_open_enter: "Deschide fișier sau intră în director",
    help_go_up: "Mergi la directorul părinte",
    help_jump10: "Salt 10 intrări", help_first_last: "Prima / ultima intrare",
    help_select: "Selectează / deselectează fișier",
    help_select_all: "Selectează tot", help_deselect_all: "Deselectează tot",
    help_copy: "Copiază selecția", help_cut: "Decupează selecția",
    help_paste: "Lipește", help_delete: "Șterge selecția (cu confirmare)",
    help_rename: "Redenumește", help_new_file: "Fișier nou",
    help_new_dir: "Director nou", help_fuzzy: "Căutare fuzzy (recursivă)",
    help_new_tab: "Deschide tab nou", help_close_tab: "Închide tabul curent",
    help_cycle_tab: "Treci la tabul următor",
    help_toggle_hidden: "Comută fișierele ascunse",
    help_drives: "Deschide managerul de unități / USB / telefon",
    help_drive_mount: "Montează unitatea sau telefonul selectat",
    help_drive_unmount: "Demontează unitatea sau telefonul selectat",
    help_drive_refresh: "Reîmprospătează lista de dispozitive",
    help_open_settings: "Deschide setările",
    help_show_help: "Afișează acest ajutor", help_quit: "Ieșire",
    drive_title: "Manager Unități",
    drive_no_devices: "Nu s-au detectat unități sau telefoane.",
    drive_tip_plug: "Conectați un USB sau un telefon prin USB",
    drive_tip_mtp: "Pentru telefoane Android: activați modul MTP",
    drive_tip_jmtpfs: "jmtpfs trebuie instalat pentru suport telefon",
    drive_col_name: "Nume", drive_col_size: "Mărime",
    drive_col_fs: "FS", drive_col_mount: "Punct montare",
    drive_hint_mount: "montează", drive_hint_unmount: "demontează",
    drive_hint_navigate: "navighează", drive_hint_refresh: "reîmprospătează",
    drive_hint_close: "închide",
    msg_already_mounted: "Deja montat — apasă u pentru a demonta",
    msg_cant_close_tab: "Nu se poate închide ultimul tab",
    msg_cant_navigate: "Nu se poate naviga în acest tip de partiție",
    msg_not_mounted: "Nemontat",
    msg_not_mounted_hint: "Nemontat — apasă m pentru a monta mai întâi",
    msg_nothing_to_paste: "Nimic de lipit",
    msg_nothing_to_yank: "Nimic de copiat",
    msg_pasted: "Lipit cu succes",
    msg_select_first: "Selectează fișiere mai întâi (Spațiu)",
    msg_hidden_shown: "Fișiere ascunse afișate",
    msg_hidden_hidden: "Fișiere ascunse ascunse",
    msg_copied: "copiat", msg_cut: "decupat",
    preview_folder_size: "Mărime folder", preview_items: "elemente",
    preview_item: "element", preview_computing: "…",
    msg_mounted_at: "Montat la", msg_mount_failed: "Montare eșuată",
    msg_unmounted: "Demontat", msg_unmount_failed: "Demontare eșuată",
    msg_extracted: "Extras", msg_extract_error: "Eroare extragere",
    msg_deleted: "Șters", msg_deleted_items: "element(e)",
    msg_error: "Eroare", msg_launching: "Lansare", msg_in_terminal: "în terminal",
    msg_tab_word: "Tab", msg_opened_word: "deschis",
    msg_settings_saved: "Setări salvate", msg_save_error: "Eroare salvare",
    msg_unsaved_changes: "Modificări nesalvate — apasă S pentru a salva",
    msg_extracting: "Se extrage", msg_esc_cancel: "[Esc anulare]",
};

// ── French ────────────────────────────────────────────────────────────────────
static FR: Lang = Lang {
    sec_behaviour: "Comportement", sec_appearance: "Apparence",
    sec_openers: "Ouvreurs", sec_keybinds: "Touches", sec_about: "À propos",
    set_show_hidden: "Afficher les fichiers cachés", set_date_format: "Format de date",
    set_show_clock: "Afficher l'horloge dans la barre",
    set_show_mtime: "Afficher la date/heure du fichier",
    kb_select: "Sélectionner / désélectionner", kb_select_all: "Tout sélectionner",
    kb_copy: "Copier", kb_cut: "Couper", kb_paste: "Coller",
    kb_delete: "Supprimer", kb_rename: "Renommer",
    kb_new_file: "Nouveau fichier", kb_new_dir: "Nouveau dossier",
    kb_search: "Recherche floue", kb_toggle_hidden: "Basculer fichiers cachés",
    kb_new_tab: "Nouvel onglet", kb_close_tab: "Fermer l'onglet",
    kb_cycle_tab: "Cycler les onglets", kb_quit: "Quitter",
    kb_drives: "Gestionnaire de lecteurs / USB / téléphone",
    kb_header_nav: "── Navigation ───────────────────────────",
    kb_header_sel: "── Sélection ────────────────────────────",
    kb_header_ops: "── Opérations fichiers ──────────────────",
    kb_header_tabs: "── Onglets ──────────────────────────────",
    kb_header_drives: "── Lecteurs & Appareils ─────────────────",
    kb_header_app: "── Application ──────────────────────────",
    kb_nav_up: "Haut", kb_nav_down: "Bas",
    kb_nav_left: "Retour", kb_nav_right: "Ouvrir / entrer",
    kb_page_up: "Sauter 10 haut", kb_page_down: "Sauter 10 bas",
    kb_first: "Premier", kb_last: "Dernier",
    kb_navigate: "Naviguer", kb_open: "Ouvrir / entrer dans le dossier",
    kb_go_up: "Monter", kb_jump: "Sauter 10 entrées",
    kb_first_last: "Première / dernière entrée",
    kb_deselect_all: "Tout désélectionner", kb_select_all2: "Tout sélectionner (alt)",
    kb_open_with: "Ouvrir avec…", kb_settings: "Ouvrir les paramètres",
    kb_help: "Afficher l'aide", kb_quit2: "Quitter (alt)",
    kb_drive_mount: "Monter le périphérique sélectionné",
    kb_drive_unmount: "Démonter le périphérique sélectionné",
    kb_drive_refresh: "Actualiser la liste",
    kb_trash_open: "Ouvrir la corbeille",
    kb_edit_add_one: "Ajouter une touche",
    kb_edit_add_combo: "Ajouter combinaison  (ex. Ctrl+K)",
    kb_edit_remove: "Supprimer une liaison",
    kb_edit_reset: "Rétablir par défaut",
    kb_edit_current: "Actuel",
    kb_edit_press_key: "Appuyez sur une touche — elle fonctionnera seule",
    kb_edit_step1: "Appuyez sur la PREMIÈRE touche de la combinaison",
    kb_edit_step2: "Première touche : {} — appuyez maintenant sur la DEUXIÈME touche",
    kb_edit_remove_title: "Supprimer la liaison",
    about_app: "Application", about_ver: "Version", about_author: "Auteur",
    about_license: "Licence", about_repo: "Dépôt",
    about_tagline: "Un gestionnaire de fichiers TUI au thème void onirique",
    about_built_with: "Construit avec Rust + Ratatui",
    help_navigation: "Navigation", help_file_ops: "Opérations sur les fichiers",
    help_search: "Recherche", help_tabs: "Onglets", help_app: "Application",
    help_move_cursor: "Déplacer le curseur haut / bas",
    help_open_enter: "Ouvrir un fichier ou entrer dans un dossier",
    help_go_up: "Aller au dossier parent",
    help_jump10: "Sauter 10 entrées", help_first_last: "Première / dernière entrée",
    help_select: "Sélectionner / désélectionner un fichier",
    help_select_all: "Tout sélectionner", help_deselect_all: "Tout désélectionner",
    help_copy: "Copier la sélection", help_cut: "Couper la sélection",
    help_paste: "Coller", help_delete: "Supprimer la sélection (avec confirmation)",
    help_rename: "Renommer", help_new_file: "Nouveau fichier",
    help_new_dir: "Nouveau dossier", help_fuzzy: "Recherche floue (récursive)",
    help_new_tab: "Ouvrir un nouvel onglet", help_close_tab: "Fermer l'onglet actuel",
    help_cycle_tab: "Passer à l'onglet suivant",
    help_toggle_hidden: "Basculer les fichiers cachés",
    help_drives: "Ouvrir le gestionnaire de lecteurs / USB / téléphone",
    help_drive_mount: "Monter le lecteur ou le téléphone sélectionné",
    help_drive_unmount: "Démonter le lecteur ou le téléphone sélectionné",
    help_drive_refresh: "Actualiser la liste des périphériques",
    help_open_settings: "Ouvrir les paramètres",
    help_show_help: "Afficher cette aide", help_quit: "Quitter",
    drive_title: "Gestionnaire de Lecteurs",
    drive_no_devices: "Aucun lecteur amovible ou téléphone détecté.",
    drive_tip_plug: "Branchez un USB ou connectez un téléphone via USB",
    drive_tip_mtp: "Pour les téléphones Android : activez le mode MTP",
    drive_tip_jmtpfs: "jmtpfs doit être installé pour le support téléphone",
    drive_col_name: "Nom", drive_col_size: "Taille",
    drive_col_fs: "FS", drive_col_mount: "Point de montage",
    drive_hint_mount: "monter", drive_hint_unmount: "démonter",
    drive_hint_navigate: "naviguer", drive_hint_refresh: "actualiser",
    drive_hint_close: "fermer",
    msg_already_mounted: "Déjà monté — appuyez sur u pour démonter",
    msg_cant_close_tab: "Impossible de fermer le dernier onglet",
    msg_cant_navigate: "Impossible de naviguer dans ce type de partition",
    msg_not_mounted: "Non monté",
    msg_not_mounted_hint: "Non monté — appuyez sur m pour monter d'abord",
    msg_nothing_to_paste: "Rien à coller",
    msg_nothing_to_yank: "Rien à copier",
    msg_pasted: "Collé avec succès",
    msg_select_first: "Sélectionnez d'abord des fichiers (Espace)",
    msg_hidden_shown: "Fichiers cachés affichés",
    msg_hidden_hidden: "Fichiers cachés masqués",
    msg_copied: "copié", msg_cut: "coupé",
    preview_folder_size: "Taille du dossier", preview_items: "éléments",
    preview_item: "élément", preview_computing: "…",
    msg_mounted_at: "Monté à", msg_mount_failed: "Échec du montage",
    msg_unmounted: "Démonté", msg_unmount_failed: "Échec du démontage",
    msg_extracted: "Extrait", msg_extract_error: "Erreur d'extraction",
    msg_deleted: "Supprimé", msg_deleted_items: "élément(s)",
    msg_error: "Erreur", msg_launching: "Lancement de", msg_in_terminal: "dans le terminal",
    msg_tab_word: "Onglet", msg_opened_word: "ouvert",
    msg_settings_saved: "Paramètres sauvegardés", msg_save_error: "Erreur de sauvegarde",
    msg_unsaved_changes: "Modifications non sauvegardées — appuyez sur S",
    msg_extracting: "Extraction de", msg_esc_cancel: "[Échap annuler]",
};

// ── German ────────────────────────────────────────────────────────────────────
static DE: Lang = Lang {
    sec_behaviour: "Verhalten", sec_appearance: "Aussehen",
    sec_openers: "Öffner", sec_keybinds: "Tasten", sec_about: "Über",
    set_show_hidden: "Versteckte Dateien anzeigen", set_date_format: "Datumsformat",
    set_show_clock: "Uhr in der Tab-Leiste anzeigen",
    set_show_mtime: "Datum/Uhrzeit der Datei anzeigen",
    kb_select: "Auswählen / Abwählen", kb_select_all: "Alles auswählen",
    kb_copy: "Kopieren", kb_cut: "Ausschneiden", kb_paste: "Einfügen",
    kb_delete: "Löschen", kb_rename: "Umbenennen",
    kb_new_file: "Neue Datei", kb_new_dir: "Neuer Ordner",
    kb_search: "Unscharfe Suche", kb_toggle_hidden: "Versteckte Dateien umschalten",
    kb_new_tab: "Neuer Tab", kb_close_tab: "Tab schließen",
    kb_cycle_tab: "Tabs wechseln", kb_quit: "Beenden",
    kb_drives: "Laufwerk / USB / Telefon-Manager",
    kb_header_nav: "── Navigation ───────────────────────────",
    kb_header_sel: "── Auswahl ──────────────────────────────",
    kb_header_ops: "── Dateioperationen ─────────────────────",
    kb_header_tabs: "── Tabs ─────────────────────────────────",
    kb_header_drives: "── Laufwerke & Geräte ───────────────────",
    kb_header_app: "── App ──────────────────────────────────",
    kb_nav_up: "Hoch", kb_nav_down: "Runter",
    kb_nav_left: "Zurück", kb_nav_right: "Öffnen / Eintreten",
    kb_page_up: "10 hoch", kb_page_down: "10 runter",
    kb_first: "Erster Eintrag", kb_last: "Letzter Eintrag",
    kb_navigate: "Navigieren", kb_open: "Öffnen / in Verz. eintreten",
    kb_go_up: "Nach oben", kb_jump: "10 Einträge springen",
    kb_first_last: "Erster / letzter Eintrag",
    kb_deselect_all: "Alles abwählen", kb_select_all2: "Alles auswählen (alt)",
    kb_open_with: "Öffnen mit…", kb_settings: "Einstellungen öffnen",
    kb_help: "Hilfe anzeigen", kb_quit2: "Beenden (alt)",
    kb_drive_mount: "Ausgewähltes Gerät einbinden",
    kb_drive_unmount: "Ausgewähltes Gerät aushängen",
    kb_drive_refresh: "Geräteliste aktualisieren",
    kb_trash_open: "Papierkorb öffnen",
    kb_edit_add_one: "Eine Taste hinzufügen",
    kb_edit_add_combo: "Kombination hinzufügen  (z.B. Ctrl+K)",
    kb_edit_remove: "Bindung entfernen",
    kb_edit_reset: "Standard zurücksetzen",
    kb_edit_current: "Aktuell",
    kb_edit_press_key: "Beliebige Taste drücken — sie funktioniert alleine",
    kb_edit_step1: "ERSTE Taste der Kombination drücken",
    kb_edit_step2: "Erste Taste: {} — jetzt ZWEITE Taste drücken",
    kb_edit_remove_title: "Bindung entfernen",
    about_app: "Anwendung", about_ver: "Version", about_author: "Autor",
    about_license: "Lizenz", about_repo: "Repository",
    about_tagline: "Ein traumhafter void-thematisierter TUI-Dateimanager",
    about_built_with: "Erstellt mit Rust + Ratatui",
    help_navigation: "Navigation", help_file_ops: "Dateioperationen",
    help_search: "Suche", help_tabs: "Tabs", help_app: "Anwendung",
    help_move_cursor: "Cursor hoch / runter bewegen",
    help_open_enter: "Datei öffnen oder Verzeichnis betreten",
    help_go_up: "Zum übergeordneten Verzeichnis",
    help_jump10: "10 Einträge springen", help_first_last: "Erster / letzter Eintrag",
    help_select: "Datei auswählen / abwählen",
    help_select_all: "Alles auswählen", help_deselect_all: "Alles abwählen",
    help_copy: "Auswahl kopieren", help_cut: "Auswahl ausschneiden",
    help_paste: "Einfügen", help_delete: "Auswahl löschen (mit Bestätigung)",
    help_rename: "Umbenennen", help_new_file: "Neue Datei",
    help_new_dir: "Neuer Ordner", help_fuzzy: "Unscharfe Suche (rekursiv)",
    help_new_tab: "Neuen Tab öffnen", help_close_tab: "Aktuellen Tab schließen",
    help_cycle_tab: "Zum nächsten Tab wechseln",
    help_toggle_hidden: "Versteckte Dateien umschalten",
    help_drives: "Laufwerk / USB / Telefon-Manager öffnen",
    help_drive_mount: "Ausgewähltes Laufwerk oder Telefon einbinden",
    help_drive_unmount: "Ausgewähltes Laufwerk oder Telefon aushängen",
    help_drive_refresh: "Geräteliste aktualisieren",
    help_open_settings: "Einstellungen öffnen",
    help_show_help: "Diese Hilfe anzeigen", help_quit: "Beenden",
    drive_title: "Laufwerk-Manager",
    drive_no_devices: "Keine Wechsellaufwerke oder Telefone erkannt.",
    drive_tip_plug: "USB-Laufwerk anschließen oder Telefon per USB verbinden",
    drive_tip_mtp: "Für Android-Telefone: MTP-Modus aktivieren",
    drive_tip_jmtpfs: "jmtpfs muss für Telefonunterstützung installiert sein",
    drive_col_name: "Name", drive_col_size: "Größe",
    drive_col_fs: "FS", drive_col_mount: "Einhängepunkt",
    drive_hint_mount: "einbinden", drive_hint_unmount: "aushängen",
    drive_hint_navigate: "navigieren", drive_hint_refresh: "aktualisieren",
    drive_hint_close: "schließen",
    msg_already_mounted: "Bereits eingebunden — u zum Aushängen drücken",
    msg_cant_close_tab: "Letzten Tab kann nicht geschlossen werden",
    msg_cant_navigate: "Kann nicht in diesen Partitionstyp navigieren",
    msg_not_mounted: "Nicht eingebunden",
    msg_not_mounted_hint: "Nicht eingebunden — erst m zum Einbinden drücken",
    msg_nothing_to_paste: "Nichts zum Einfügen",
    msg_nothing_to_yank: "Nichts zum Kopieren",
    msg_pasted: "Erfolgreich eingefügt",
    msg_select_first: "Zuerst Dateien auswählen (Leertaste)",
    msg_hidden_shown: "Versteckte Dateien angezeigt",
    msg_hidden_hidden: "Versteckte Dateien ausgeblendet",
    msg_copied: "kopiert", msg_cut: "ausgeschnitten",
    preview_folder_size: "Ordnergröße", preview_items: "Elemente",
    preview_item: "Element", preview_computing: "…",
    msg_mounted_at: "Eingebunden unter", msg_mount_failed: "Einbindung fehlgeschlagen",
    msg_unmounted: "Ausgehängt", msg_unmount_failed: "Aushängen fehlgeschlagen",
    msg_extracted: "Entpackt", msg_extract_error: "Entpackfehler",
    msg_deleted: "Gelöscht", msg_deleted_items: "Element(e)",
    msg_error: "Fehler", msg_launching: "Starte", msg_in_terminal: "im Terminal",
    msg_tab_word: "Tab", msg_opened_word: "geöffnet",
    msg_settings_saved: "Einstellungen gespeichert", msg_save_error: "Speicherfehler",
    msg_unsaved_changes: "Ungespeicherte Änderungen — S zum Speichern",
    msg_extracting: "Entpacke", msg_esc_cancel: "[Esc abbrechen]",
};

// ── Spanish ───────────────────────────────────────────────────────────────────
static ES: Lang = Lang {
    sec_behaviour: "Comportamiento", sec_appearance: "Apariencia",
    sec_openers: "Abridores", sec_keybinds: "Teclas", sec_about: "Acerca de",
    set_show_hidden: "Mostrar archivos ocultos", set_date_format: "Formato de fecha",
    set_show_clock: "Mostrar reloj en la barra de pestañas",
    set_show_mtime: "Mostrar fecha/hora del archivo",
    kb_select: "Seleccionar / deseleccionar", kb_select_all: "Seleccionar todo",
    kb_copy: "Copiar", kb_cut: "Cortar", kb_paste: "Pegar",
    kb_delete: "Eliminar", kb_rename: "Renombrar",
    kb_new_file: "Nuevo archivo", kb_new_dir: "Nueva carpeta",
    kb_search: "Búsqueda difusa", kb_toggle_hidden: "Alternar archivos ocultos",
    kb_new_tab: "Nueva pestaña", kb_close_tab: "Cerrar pestaña",
    kb_cycle_tab: "Rotar pestañas", kb_quit: "Salir",
    kb_drives: "Gestor de unidades / USB / teléfono",
    kb_header_nav: "── Navegación ───────────────────────────",
    kb_header_sel: "── Selección ────────────────────────────",
    kb_header_ops: "── Operaciones de archivo ───────────────",
    kb_header_tabs: "── Pestañas ─────────────────────────────",
    kb_header_drives: "── Unidades y dispositivos ──────────────",
    kb_header_app: "── Aplicación ───────────────────────────",
    kb_nav_up: "Arriba", kb_nav_down: "Abajo",
    kb_nav_left: "Atrás", kb_nav_right: "Abrir / entrar",
    kb_page_up: "Saltar 10 arriba", kb_page_down: "Saltar 10 abajo",
    kb_first: "Primera entrada", kb_last: "Última entrada",
    kb_navigate: "Navegar", kb_open: "Abrir / entrar en directorio",
    kb_go_up: "Subir", kb_jump: "Saltar 10 entradas",
    kb_first_last: "Primera / última entrada",
    kb_deselect_all: "Deseleccionar todo", kb_select_all2: "Seleccionar todo (alt)",
    kb_open_with: "Abrir con…", kb_settings: "Abrir ajustes",
    kb_help: "Mostrar ayuda", kb_quit2: "Salir (alt)",
    kb_drive_mount: "Montar dispositivo seleccionado",
    kb_drive_unmount: "Desmontar dispositivo seleccionado",
    kb_drive_refresh: "Actualizar lista de dispositivos",
    kb_trash_open: "Abrir papelera",
    kb_edit_add_one: "Añadir una tecla",
    kb_edit_add_combo: "Añadir combinación  (ej. Ctrl+K)",
    kb_edit_remove: "Eliminar una asignación",
    kb_edit_reset: "Restablecer predeterminado",
    kb_edit_current: "Actual",
    kb_edit_press_key: "Presiona cualquier tecla — funcionará sola",
    kb_edit_step1: "Presiona la PRIMERA tecla de la combinación",
    kb_edit_step2: "Primera tecla: {} — ahora presiona la SEGUNDA tecla",
    kb_edit_remove_title: "Eliminar asignación",
    about_app: "Aplicación", about_ver: "Versión", about_author: "Autor",
    about_license: "Licencia", about_repo: "Repositorio",
    about_tagline: "Un gestor de archivos TUI con tema void onírico",
    about_built_with: "Construido con Rust + Ratatui",
    help_navigation: "Navegación", help_file_ops: "Operaciones de archivo",
    help_search: "Búsqueda", help_tabs: "Pestañas", help_app: "Aplicación",
    help_move_cursor: "Mover cursor arriba / abajo",
    help_open_enter: "Abrir archivo o entrar en directorio",
    help_go_up: "Ir al directorio padre",
    help_jump10: "Saltar 10 entradas", help_first_last: "Primera / última entrada",
    help_select: "Seleccionar / deseleccionar archivo",
    help_select_all: "Seleccionar todo", help_deselect_all: "Deseleccionar todo",
    help_copy: "Copiar selección", help_cut: "Cortar selección",
    help_paste: "Pegar", help_delete: "Eliminar selección (con confirmación)",
    help_rename: "Renombrar", help_new_file: "Nuevo archivo",
    help_new_dir: "Nueva carpeta", help_fuzzy: "Búsqueda difusa (recursiva)",
    help_new_tab: "Abrir nueva pestaña", help_close_tab: "Cerrar pestaña actual",
    help_cycle_tab: "Pasar a la siguiente pestaña",
    help_toggle_hidden: "Alternar archivos ocultos",
    help_drives: "Abrir gestor de unidades / USB / teléfono",
    help_drive_mount: "Montar unidad o teléfono seleccionado",
    help_drive_unmount: "Desmontar unidad o teléfono seleccionado",
    help_drive_refresh: "Actualizar lista de dispositivos",
    help_open_settings: "Abrir ajustes",
    help_show_help: "Mostrar esta ayuda", help_quit: "Salir",
    drive_title: "Gestor de Unidades",
    drive_no_devices: "No se detectaron unidades extraíbles ni teléfonos.",
    drive_tip_plug: "Conecte un USB o un teléfono mediante USB",
    drive_tip_mtp: "Para teléfonos Android: active el modo MTP",
    drive_tip_jmtpfs: "jmtpfs debe estar instalado para soporte de teléfono",
    drive_col_name: "Nombre", drive_col_size: "Tamaño",
    drive_col_fs: "FS", drive_col_mount: "Punto de montaje",
    drive_hint_mount: "montar", drive_hint_unmount: "desmontar",
    drive_hint_navigate: "navegar", drive_hint_refresh: "actualizar",
    drive_hint_close: "cerrar",
    msg_already_mounted: "Ya montado — pulsa u para desmontar",
    msg_cant_close_tab: "No se puede cerrar la última pestaña",
    msg_cant_navigate: "No se puede navegar en este tipo de partición",
    msg_not_mounted: "No montado",
    msg_not_mounted_hint: "No montado — pulsa m para montar primero",
    msg_nothing_to_paste: "Nada que pegar",
    msg_nothing_to_yank: "Nada que copiar",
    msg_pasted: "Pegado correctamente",
    msg_select_first: "Selecciona archivos primero (Espacio)",
    msg_hidden_shown: "Archivos ocultos mostrados",
    msg_hidden_hidden: "Archivos ocultos ocultados",
    msg_copied: "copiado", msg_cut: "cortado",
    preview_folder_size: "Tamaño de carpeta", preview_items: "elementos",
    preview_item: "elemento", preview_computing: "…",
    msg_mounted_at: "Montado en", msg_mount_failed: "Error al montar",
    msg_unmounted: "Desmontado", msg_unmount_failed: "Error al desmontar",
    msg_extracted: "Extraído", msg_extract_error: "Error de extracción",
    msg_deleted: "Eliminado", msg_deleted_items: "elemento(s)",
    msg_error: "Error", msg_launching: "Iniciando", msg_in_terminal: "en terminal",
    msg_tab_word: "Pestaña", msg_opened_word: "abierta",
    msg_settings_saved: "Ajustes guardados", msg_save_error: "Error al guardar",
    msg_unsaved_changes: "Cambios sin guardar — pulsa S para guardar",
    msg_extracting: "Extrayendo", msg_esc_cancel: "[Esc cancelar]",
};

// ── Italian ───────────────────────────────────────────────────────────────────
static IT: Lang = Lang {
    sec_behaviour: "Comportamento", sec_appearance: "Aspetto",
    sec_openers: "Programmi", sec_keybinds: "Tasti", sec_about: "Informazioni",
    set_show_hidden: "Mostra file nascosti", set_date_format: "Formato data",
    set_show_clock: "Mostra orologio nella barra delle schede",
    set_show_mtime: "Mostra data/ora del file",
    kb_select: "Seleziona / deseleziona", kb_select_all: "Seleziona tutto",
    kb_copy: "Copia", kb_cut: "Taglia", kb_paste: "Incolla",
    kb_delete: "Elimina", kb_rename: "Rinomina",
    kb_new_file: "Nuovo file", kb_new_dir: "Nuova cartella",
    kb_search: "Ricerca fuzzy", kb_toggle_hidden: "Attiva/disattiva file nascosti",
    kb_new_tab: "Nuova scheda", kb_close_tab: "Chiudi scheda",
    kb_cycle_tab: "Ruota schede", kb_quit: "Esci",
    kb_drives: "Gestione unità / USB / telefono",
    kb_header_nav: "── Navigazione ──────────────────────────",
    kb_header_sel: "── Selezione ────────────────────────────",
    kb_header_ops: "── Operazioni file ──────────────────────",
    kb_header_tabs: "── Schede ───────────────────────────────",
    kb_header_drives: "── Unità e dispositivi ──────────────────",
    kb_header_app: "── App ──────────────────────────────────",
    kb_nav_up: "Su", kb_nav_down: "Giù",
    kb_nav_left: "Indietro", kb_nav_right: "Apri / entra",
    kb_page_up: "Salta 10 su", kb_page_down: "Salta 10 giù",
    kb_first: "Prima voce", kb_last: "Ultima voce",
    kb_navigate: "Naviga", kb_open: "Apri / entra nella cartella",
    kb_go_up: "Su", kb_jump: "Salta 10 voci",
    kb_first_last: "Prima / ultima voce",
    kb_deselect_all: "Deseleziona tutto", kb_select_all2: "Seleziona tutto (alt)",
    kb_open_with: "Apri con…", kb_settings: "Apri impostazioni",
    kb_help: "Mostra aiuto", kb_quit2: "Esci (alt)",
    kb_drive_mount: "Monta dispositivo selezionato",
    kb_drive_unmount: "Smonta dispositivo selezionato",
    kb_drive_refresh: "Aggiorna lista dispositivi",
    kb_trash_open: "Apri cestino",
    kb_edit_add_one: "Aggiungi un tasto",
    kb_edit_add_combo: "Aggiungi combinazione  (es. Ctrl+K)",
    kb_edit_remove: "Rimuovi assegnazione",
    kb_edit_reset: "Ripristina predefinito",
    kb_edit_current: "Corrente",
    kb_edit_press_key: "Premi qualsiasi tasto — funzionerà da solo",
    kb_edit_step1: "Premi il PRIMO tasto della combinazione",
    kb_edit_step2: "Primo tasto: {} — ora premi il SECONDO tasto",
    kb_edit_remove_title: "Rimuovi assegnazione",
    about_app: "Applicazione", about_ver: "Versione", about_author: "Autore",
    about_license: "Licenza", about_repo: "Repository",
    about_tagline: "Un gestore di file TUI con tema void onirico",
    about_built_with: "Costruito con Rust + Ratatui",
    help_navigation: "Navigazione", help_file_ops: "Operazioni sui file",
    help_search: "Ricerca", help_tabs: "Schede", help_app: "Applicazione",
    help_move_cursor: "Sposta cursore su / giù",
    help_open_enter: "Apri file o entra nella cartella",
    help_go_up: "Vai alla cartella principale",
    help_jump10: "Salta 10 voci", help_first_last: "Prima / ultima voce",
    help_select: "Seleziona / deseleziona file",
    help_select_all: "Seleziona tutto", help_deselect_all: "Deseleziona tutto",
    help_copy: "Copia selezione", help_cut: "Taglia selezione",
    help_paste: "Incolla", help_delete: "Elimina selezione (con conferma)",
    help_rename: "Rinomina", help_new_file: "Nuovo file",
    help_new_dir: "Nuova cartella", help_fuzzy: "Ricerca fuzzy (ricorsiva)",
    help_new_tab: "Apri nuova scheda", help_close_tab: "Chiudi scheda corrente",
    help_cycle_tab: "Passa alla scheda successiva",
    help_toggle_hidden: "Attiva/disattiva file nascosti",
    help_drives: "Apri gestione unità / USB / telefono",
    help_drive_mount: "Monta unità o telefono selezionato",
    help_drive_unmount: "Smonta unità o telefono selezionato",
    help_drive_refresh: "Aggiorna lista dispositivi",
    help_open_settings: "Apri impostazioni",
    help_show_help: "Mostra questa guida", help_quit: "Esci",
    drive_title: "Gestione Unità",
    drive_no_devices: "Nessuna unità rimovibile o telefono rilevato.",
    drive_tip_plug: "Collega un USB o un telefono tramite USB",
    drive_tip_mtp: "Per telefoni Android: attiva la modalità MTP",
    drive_tip_jmtpfs: "jmtpfs deve essere installato per il supporto telefono",
    drive_col_name: "Nome", drive_col_size: "Dimensione",
    drive_col_fs: "FS", drive_col_mount: "Punto di montaggio",
    drive_hint_mount: "monta", drive_hint_unmount: "smonta",
    drive_hint_navigate: "naviga", drive_hint_refresh: "aggiorna",
    drive_hint_close: "chiudi",
    msg_already_mounted: "Già montato — premi u per smontare",
    msg_cant_close_tab: "Impossibile chiudere l'ultima scheda",
    msg_cant_navigate: "Impossibile navigare in questo tipo di partizione",
    msg_not_mounted: "Non montato",
    msg_not_mounted_hint: "Non montato — premi m per montare prima",
    msg_nothing_to_paste: "Niente da incollare",
    msg_nothing_to_yank: "Niente da copiare",
    msg_pasted: "Incollato con successo",
    msg_select_first: "Seleziona prima i file (Spazio)",
    msg_hidden_shown: "File nascosti mostrati",
    msg_hidden_hidden: "File nascosti nascosti",
    msg_copied: "copiato", msg_cut: "tagliato",
    preview_folder_size: "Dimensione cartella", preview_items: "elementi",
    preview_item: "elemento", preview_computing: "…",
    msg_mounted_at: "Montato in", msg_mount_failed: "Montaggio fallito",
    msg_unmounted: "Smontato", msg_unmount_failed: "Smontaggio fallito",
    msg_extracted: "Estratto", msg_extract_error: "Errore estrazione",
    msg_deleted: "Eliminato", msg_deleted_items: "elemento/i",
    msg_error: "Errore", msg_launching: "Avvio di", msg_in_terminal: "nel terminale",
    msg_tab_word: "Scheda", msg_opened_word: "aperta",
    msg_settings_saved: "Impostazioni salvate", msg_save_error: "Errore salvataggio",
    msg_unsaved_changes: "Modifiche non salvate — premi S per salvare",
    msg_extracting: "Estrazione di", msg_esc_cancel: "[Esc annulla]",
};

// ── Portuguese ────────────────────────────────────────────────────────────────
static PT: Lang = Lang {
    sec_behaviour: "Comportamento", sec_appearance: "Aparência",
    sec_openers: "Abridores", sec_keybinds: "Teclas", sec_about: "Sobre",
    set_show_hidden: "Mostrar ficheiros ocultos", set_date_format: "Formato de data",
    set_show_clock: "Mostrar relógio na barra de separadores",
    set_show_mtime: "Mostrar data/hora do ficheiro",
    kb_select: "Selecionar / desselecionar", kb_select_all: "Selecionar tudo",
    kb_copy: "Copiar", kb_cut: "Cortar", kb_paste: "Colar",
    kb_delete: "Eliminar", kb_rename: "Renomear",
    kb_new_file: "Novo ficheiro", kb_new_dir: "Nova pasta",
    kb_search: "Pesquisa difusa", kb_toggle_hidden: "Alternar ficheiros ocultos",
    kb_new_tab: "Novo separador", kb_close_tab: "Fechar separador",
    kb_cycle_tab: "Rodar separadores", kb_quit: "Sair",
    kb_drives: "Gestor de unidades / USB / telefone",
    kb_header_nav: "── Navegação ────────────────────────────",
    kb_header_sel: "── Seleção ──────────────────────────────",
    kb_header_ops: "── Operações de arquivo ─────────────────",
    kb_header_tabs: "── Abas ─────────────────────────────────",
    kb_header_drives: "── Unidades e dispositivos ──────────────",
    kb_header_app: "── Aplicativo ───────────────────────────",
    kb_nav_up: "Cima", kb_nav_down: "Baixo",
    kb_nav_left: "Voltar", kb_nav_right: "Abrir / entrar",
    kb_page_up: "Pular 10 cima", kb_page_down: "Pular 10 baixo",
    kb_first: "Primeira entrada", kb_last: "Última entrada",
    kb_navigate: "Navegar", kb_open: "Abrir / entrar na pasta",
    kb_go_up: "Subir", kb_jump: "Saltar 10 entradas",
    kb_first_last: "Primeira / última entrada",
    kb_deselect_all: "Desselecionar tudo", kb_select_all2: "Selecionar tudo (alt)",
    kb_open_with: "Abrir com…", kb_settings: "Abrir definições",
    kb_help: "Mostrar ajuda", kb_quit2: "Sair (alt)",
    kb_drive_mount: "Montar dispositivo selecionado",
    kb_drive_unmount: "Desmontar dispositivo selecionado",
    kb_drive_refresh: "Atualizar lista de dispositivos",
    kb_trash_open: "Abrir lixeira",
    kb_edit_add_one: "Adicionar uma tecla",
    kb_edit_add_combo: "Adicionar combinação  (ex. Ctrl+K)",
    kb_edit_remove: "Remover atribuição",
    kb_edit_reset: "Redefinir padrão",
    kb_edit_current: "Atual",
    kb_edit_press_key: "Pressione qualquer tecla — funcionará sozinha",
    kb_edit_step1: "Pressione a PRIMEIRA tecla da combinação",
    kb_edit_step2: "Primeira tecla: {} — agora pressione a SEGUNDA tecla",
    kb_edit_remove_title: "Remover atribuição",
    about_app: "Aplicação", about_ver: "Versão", about_author: "Autor",
    about_license: "Licença", about_repo: "Repositório",
    about_tagline: "Um gestor de ficheiros TUI com tema void onírico",
    about_built_with: "Construído com Rust + Ratatui",
    help_navigation: "Navegação", help_file_ops: "Operações de ficheiro",
    help_search: "Pesquisa", help_tabs: "Separadores", help_app: "Aplicação",
    help_move_cursor: "Mover cursor para cima / baixo",
    help_open_enter: "Abrir ficheiro ou entrar na pasta",
    help_go_up: "Ir para a pasta pai",
    help_jump10: "Saltar 10 entradas", help_first_last: "Primeira / última entrada",
    help_select: "Selecionar / desselecionar ficheiro",
    help_select_all: "Selecionar tudo", help_deselect_all: "Desselecionar tudo",
    help_copy: "Copiar seleção", help_cut: "Cortar seleção",
    help_paste: "Colar", help_delete: "Eliminar seleção (com confirmação)",
    help_rename: "Renomear", help_new_file: "Novo ficheiro",
    help_new_dir: "Nova pasta", help_fuzzy: "Pesquisa difusa (recursiva)",
    help_new_tab: "Abrir novo separador", help_close_tab: "Fechar separador atual",
    help_cycle_tab: "Passar para o próximo separador",
    help_toggle_hidden: "Alternar ficheiros ocultos",
    help_drives: "Abrir gestor de unidades / USB / telefone",
    help_drive_mount: "Montar unidade ou telefone selecionado",
    help_drive_unmount: "Desmontar unidade ou telefone selecionado",
    help_drive_refresh: "Atualizar lista de dispositivos",
    help_open_settings: "Abrir definições",
    help_show_help: "Mostrar esta ajuda", help_quit: "Sair",
    drive_title: "Gestor de Unidades",
    drive_no_devices: "Não foram detetadas unidades amovíveis ou telefones.",
    drive_tip_plug: "Ligue um USB ou conecte um telefone via USB",
    drive_tip_mtp: "Para telefones Android: ative o modo MTP",
    drive_tip_jmtpfs: "jmtpfs deve estar instalado para suporte a telefone",
    drive_col_name: "Nome", drive_col_size: "Tamanho",
    drive_col_fs: "FS", drive_col_mount: "Ponto de montagem",
    drive_hint_mount: "montar", drive_hint_unmount: "desmontar",
    drive_hint_navigate: "navegar", drive_hint_refresh: "atualizar",
    drive_hint_close: "fechar",
    msg_already_mounted: "Já montado — prima u para desmontar",
    msg_cant_close_tab: "Não é possível fechar o último separador",
    msg_cant_navigate: "Não é possível navegar neste tipo de partição",
    msg_not_mounted: "Não montado",
    msg_not_mounted_hint: "Não montado — prima m para montar primeiro",
    msg_nothing_to_paste: "Nada para colar",
    msg_nothing_to_yank: "Nada para copiar",
    msg_pasted: "Colado com sucesso",
    msg_select_first: "Selecione ficheiros primeiro (Espaço)",
    msg_hidden_shown: "Ficheiros ocultos mostrados",
    msg_hidden_hidden: "Ficheiros ocultos ocultados",
    msg_copied: "copiado", msg_cut: "cortado",
    preview_folder_size: "Tamanho da pasta", preview_items: "itens",
    preview_item: "item", preview_computing: "…",
    msg_mounted_at: "Montado em", msg_mount_failed: "Falha ao montar",
    msg_unmounted: "Desmontado", msg_unmount_failed: "Falha ao desmontar",
    msg_extracted: "Extraído", msg_extract_error: "Erro de extração",
    msg_deleted: "Eliminado", msg_deleted_items: "item(ns)",
    msg_error: "Erro", msg_launching: "A iniciar", msg_in_terminal: "no terminal",
    msg_tab_word: "Separador", msg_opened_word: "aberto",
    msg_settings_saved: "Definições guardadas", msg_save_error: "Erro ao guardar",
    msg_unsaved_changes: "Alterações não guardadas — prima S para guardar",
    msg_extracting: "A extrair", msg_esc_cancel: "[Esc cancelar]",
};

// ── Russian ───────────────────────────────────────────────────────────────────
static RU: Lang = Lang {
    sec_behaviour: "Поведение", sec_appearance: "Внешний вид",
    sec_openers: "Открыватели", sec_keybinds: "Клавиши", sec_about: "О программе",
    set_show_hidden: "Показывать скрытые файлы", set_date_format: "Формат даты",
    set_show_clock: "Показывать часы на панели вкладок",
    set_show_mtime: "Показывать дату/время файла",
    kb_select: "Выбрать / снять выбор", kb_select_all: "Выбрать всё",
    kb_copy: "Копировать", kb_cut: "Вырезать", kb_paste: "Вставить",
    kb_delete: "Удалить", kb_rename: "Переименовать",
    kb_new_file: "Новый файл", kb_new_dir: "Новая папка",
    kb_search: "Нечёткий поиск", kb_toggle_hidden: "Скрытые файлы",
    kb_new_tab: "Новая вкладка", kb_close_tab: "Закрыть вкладку",
    kb_cycle_tab: "Переключить вкладки", kb_quit: "Выйти",
    kb_drives: "Менеджер дисков / USB / телефона",
    kb_header_nav: "── Навигация ────────────────────────────",
    kb_header_sel: "── Выделение ────────────────────────────",
    kb_header_ops: "── Операции с файлами ───────────────────",
    kb_header_tabs: "── Вкладки ──────────────────────────────",
    kb_header_drives: "── Диски и устройства ───────────────────",
    kb_header_app: "── Приложение ───────────────────────────",
    kb_nav_up: "Вверх", kb_nav_down: "Вниз",
    kb_nav_left: "Назад", kb_nav_right: "Открыть / войти",
    kb_page_up: "10 вверх", kb_page_down: "10 вниз",
    kb_first: "Первая запись", kb_last: "Последняя запись",
    kb_navigate: "Навигация", kb_open: "Открыть / войти в папку",
    kb_go_up: "Вверх", kb_jump: "Прыжок на 10 записей",
    kb_first_last: "Первая / последняя запись",
    kb_deselect_all: "Снять всё", kb_select_all2: "Выбрать всё (alt)",
    kb_open_with: "Открыть с помощью…", kb_settings: "Настройки",
    kb_help: "Показать справку", kb_quit2: "Выйти (alt)",
    kb_drive_mount: "Подключить выбранное устройство",
    kb_drive_unmount: "Отключить выбранное устройство",
    kb_drive_refresh: "Обновить список устройств",
    kb_trash_open: "Открыть корзину",
    kb_edit_add_one: "Добавить одну клавишу",
    kb_edit_add_combo: "Добавить комбинацию  (напр. Ctrl+K)",
    kb_edit_remove: "Удалить привязку",
    kb_edit_reset: "Сбросить по умолчанию",
    kb_edit_current: "Текущее",
    kb_edit_press_key: "Нажмите любую клавишу — она будет работать отдельно",
    kb_edit_step1: "Нажмите ПЕРВУЮ клавишу комбинации",
    kb_edit_step2: "Первая клавиша: {} — теперь нажмите ВТОРУЮ клавишу",
    kb_edit_remove_title: "Удалить привязку",
    about_app: "Приложение", about_ver: "Версия", about_author: "Автор",
    about_license: "Лицензия", about_repo: "Репозиторий",
    about_tagline: "Мечтательный TUI файловый менеджер в стиле void",
    about_built_with: "Создан на Rust + Ratatui",
    help_navigation: "Навигация", help_file_ops: "Операции с файлами",
    help_search: "Поиск", help_tabs: "Вкладки", help_app: "Приложение",
    help_move_cursor: "Переместить курсор вверх / вниз",
    help_open_enter: "Открыть файл или войти в папку",
    help_go_up: "Перейти в родительскую папку",
    help_jump10: "Прыжок на 10 записей",
    help_first_last: "Первая / последняя запись",
    help_select: "Выбрать / снять выбор файла",
    help_select_all: "Выбрать всё", help_deselect_all: "Снять всё",
    help_copy: "Копировать выделение", help_cut: "Вырезать выделение",
    help_paste: "Вставить", help_delete: "Удалить выделение (с подтверждением)",
    help_rename: "Переименовать", help_new_file: "Новый файл",
    help_new_dir: "Новая папка", help_fuzzy: "Нечёткий поиск (рекурсивный)",
    help_new_tab: "Открыть новую вкладку",
    help_close_tab: "Закрыть текущую вкладку",
    help_cycle_tab: "Перейти к следующей вкладке",
    help_toggle_hidden: "Скрытые файлы",
    help_drives: "Открыть менеджер дисков / USB / телефона",
    help_drive_mount: "Подключить выбранный диск или телефон",
    help_drive_unmount: "Отключить выбранный диск или телефон",
    help_drive_refresh: "Обновить список устройств",
    help_open_settings: "Открыть настройки",
    help_show_help: "Показать эту справку", help_quit: "Выйти",
    drive_title: "Менеджер Дисков",
    drive_no_devices: "Съёмные диски или телефоны не обнаружены.",
    drive_tip_plug: "Подключите USB или телефон через USB",
    drive_tip_mtp: "Для Android: включите режим MTP на телефоне",
    drive_tip_jmtpfs: "Для поддержки телефона необходим jmtpfs",
    drive_col_name: "Имя", drive_col_size: "Размер",
    drive_col_fs: "ФС", drive_col_mount: "Точка монтирования",
    drive_hint_mount: "подключить", drive_hint_unmount: "отключить",
    drive_hint_navigate: "открыть", drive_hint_refresh: "обновить",
    drive_hint_close: "закрыть",
    msg_already_mounted: "Уже подключено — нажмите u для отключения",
    msg_cant_close_tab: "Нельзя закрыть последнюю вкладку",
    msg_cant_navigate: "Невозможно открыть этот тип раздела",
    msg_not_mounted: "Не подключено",
    msg_not_mounted_hint: "Не подключено — нажмите m для подключения",
    msg_nothing_to_paste: "Нечего вставлять",
    msg_nothing_to_yank: "Нечего копировать",
    msg_pasted: "Вставлено успешно",
    msg_select_first: "Сначала выберите файлы (Пробел)",
    msg_hidden_shown: "Скрытые файлы показаны",
    msg_hidden_hidden: "Скрытые файлы скрыты",
    msg_copied: "скопировано", msg_cut: "вырезано",
    preview_folder_size: "Размер папки", preview_items: "элементов",
    preview_item: "элемент", preview_computing: "…",
    msg_mounted_at: "Подключено в", msg_mount_failed: "Ошибка подключения",
    msg_unmounted: "Отключено", msg_unmount_failed: "Ошибка отключения",
    msg_extracted: "Извлечено", msg_extract_error: "Ошибка извлечения",
    msg_deleted: "Удалено", msg_deleted_items: "эл.",
    msg_error: "Ошибка", msg_launching: "Запуск", msg_in_terminal: "в терминале",
    msg_tab_word: "Вкладка", msg_opened_word: "открыта",
    msg_settings_saved: "Настройки сохранены", msg_save_error: "Ошибка сохранения",
    msg_unsaved_changes: "Несохранённые изменения — нажмите S",
    msg_extracting: "Извлечение", msg_esc_cancel: "[Esc отмена]",
};

// ── Japanese ──────────────────────────────────────────────────────────────────
static JA: Lang = Lang {
    sec_behaviour: "動作", sec_appearance: "外観",
    sec_openers: "オープナー", sec_keybinds: "キー設定", sec_about: "情報",
    set_show_hidden: "隠しファイルを表示", set_date_format: "日付形式",
    set_show_clock: "タブバーに時計を表示", set_show_mtime: "ファイルの日時を表示",
    kb_select: "選択 / 選択解除", kb_select_all: "すべて選択",
    kb_copy: "コピー", kb_cut: "切り取り", kb_paste: "貼り付け",
    kb_delete: "削除", kb_rename: "名前変更",
    kb_new_file: "新規ファイル", kb_new_dir: "新規フォルダ",
    kb_search: "あいまい検索", kb_toggle_hidden: "隠しファイル切替",
    kb_new_tab: "新規タブ", kb_close_tab: "タブを閉じる",
    kb_cycle_tab: "タブ切替", kb_quit: "終了",
    kb_drives: "ドライブ / USB / 電話マネージャー",
    kb_header_nav: "── ナビゲーション ────────────────────────",
    kb_header_sel: "── 選択 ─────────────────────────────────",
    kb_header_ops: "── ファイル操作 ──────────────────────────",
    kb_header_tabs: "── タブ ─────────────────────────────────",
    kb_header_drives: "── ドライブとデバイス ────────────────────",
    kb_header_app: "── アプリ ───────────────────────────────",
    kb_nav_up: "上へ", kb_nav_down: "下へ",
    kb_nav_left: "戻る", kb_nav_right: "開く / 入る",
    kb_page_up: "10上へ", kb_page_down: "10下へ",
    kb_first: "最初のエントリ", kb_last: "最後のエントリ",
    kb_navigate: "ナビゲート", kb_open: "開く / フォルダに入る",
    kb_go_up: "上へ", kb_jump: "10件ジャンプ",
    kb_first_last: "最初 / 最後",
    kb_deselect_all: "すべて解除", kb_select_all2: "すべて選択 (alt)",
    kb_open_with: "アプリで開く…", kb_settings: "設定を開く",
    kb_help: "ヘルプを表示", kb_quit2: "終了 (alt)",
    kb_drive_mount: "選択デバイスをマウント",
    kb_drive_unmount: "選択デバイスをアンマウント",
    kb_drive_refresh: "デバイス一覧を更新",
    kb_trash_open: "ゴミ箱を開く",
    kb_edit_add_one: "キーを1つ追加",
    kb_edit_add_combo: "組み合わせを追加  (例: Ctrl+K)",
    kb_edit_remove: "バインドを削除",
    kb_edit_reset: "デフォルトにリセット",
    kb_edit_current: "現在",
    kb_edit_press_key: "任意のキーを押してください — 単独で動作します",
    kb_edit_step1: "組み合わせの最初のキーを押してください",
    kb_edit_step2: "最初のキー: {} — 次に2番目のキーを押してください",
    kb_edit_remove_title: "バインドを削除",
    about_app: "アプリ", about_ver: "バージョン", about_author: "作者",
    about_license: "ライセンス", about_repo: "リポジトリ",
    about_tagline: "夢のようなvoidテーマのTUIファイルマネージャー",
    about_built_with: "Rust + Ratatui で構築",
    help_navigation: "ナビゲーション", help_file_ops: "ファイル操作",
    help_search: "検索", help_tabs: "タブ", help_app: "アプリ",
    help_move_cursor: "カーソルを上 / 下に移動",
    help_open_enter: "ファイルを開くまたはフォルダに入る",
    help_go_up: "親フォルダへ移動",
    help_jump10: "10件ジャンプ", help_first_last: "最初 / 最後",
    help_select: "ファイルを選択 / 解除",
    help_select_all: "すべて選択", help_deselect_all: "すべて解除",
    help_copy: "選択をコピー", help_cut: "選択を切り取り",
    help_paste: "貼り付け", help_delete: "選択を削除 (確認あり)",
    help_rename: "名前変更", help_new_file: "新規ファイル",
    help_new_dir: "新規フォルダ", help_fuzzy: "あいまい検索 (再帰的)",
    help_new_tab: "新規タブを開く", help_close_tab: "現在のタブを閉じる",
    help_cycle_tab: "次のタブへ",
    help_toggle_hidden: "隠しファイルを切替",
    help_drives: "ドライブ / USB / 電話マネージャーを開く",
    help_drive_mount: "選択したドライブまたは電話をマウント",
    help_drive_unmount: "選択したドライブまたは電話をアンマウント",
    help_drive_refresh: "デバイス一覧を更新",
    help_open_settings: "設定を開く",
    help_show_help: "このヘルプを表示", help_quit: "終了",
    drive_title: "ドライブマネージャー",
    drive_no_devices: "リムーバブルドライブまたは電話が検出されません。",
    drive_tip_plug: "USBドライブを挿すか電話をUSBで接続してください",
    drive_tip_mtp: "Androidの場合：MTPモードを有効にしてください",
    drive_tip_jmtpfs: "電話サポートにはjmtpfsが必要です",
    drive_col_name: "名前", drive_col_size: "サイズ",
    drive_col_fs: "FS", drive_col_mount: "マウントポイント",
    drive_hint_mount: "マウント", drive_hint_unmount: "アンマウント",
    drive_hint_navigate: "移動", drive_hint_refresh: "更新",
    drive_hint_close: "閉じる",
    msg_already_mounted: "既にマウント済み — uでアンマウント",
    msg_cant_close_tab: "最後のタブは閉じられません",
    msg_cant_navigate: "このパーティションタイプには移動できません",
    msg_not_mounted: "マウントされていません",
    msg_not_mounted_hint: "未マウント — mでマウントしてください",
    msg_nothing_to_paste: "貼り付けるものがありません",
    msg_nothing_to_yank: "コピーするものがありません",
    msg_pasted: "貼り付け完了",
    msg_select_first: "先にファイルを選択してください (Space)",
    msg_hidden_shown: "隠しファイルを表示中",
    msg_hidden_hidden: "隠しファイルを非表示",
    msg_copied: "コピー済み", msg_cut: "切り取り済み",
    preview_folder_size: "フォルダサイズ", preview_items: "件",
    preview_item: "件", preview_computing: "…",
    msg_mounted_at: "マウント先", msg_mount_failed: "マウント失敗",
    msg_unmounted: "アンマウント完了", msg_unmount_failed: "アンマウント失敗",
    msg_extracted: "展開完了", msg_extract_error: "展開エラー",
    msg_deleted: "削除完了", msg_deleted_items: "件",
    msg_error: "エラー", msg_launching: "起動中", msg_in_terminal: "ターミナルで",
    msg_tab_word: "タブ", msg_opened_word: "開いた",
    msg_settings_saved: "設定を保存しました", msg_save_error: "保存エラー",
    msg_unsaved_changes: "未保存の変更 — Sで保存",
    msg_extracting: "展開中", msg_esc_cancel: "[Esc キャンセル]",
};

// ── Chinese (Simplified) ──────────────────────────────────────────────────────
static ZH: Lang = Lang {
    sec_behaviour: "行为", sec_appearance: "外观",
    sec_openers: "打开方式", sec_keybinds: "快捷键", sec_about: "关于",
    set_show_hidden: "显示隐藏文件", set_date_format: "日期格式",
    set_show_clock: "在标签栏显示时钟", set_show_mtime: "显示文件日期/时间",
    kb_select: "选择 / 取消选择", kb_select_all: "全选",
    kb_copy: "复制", kb_cut: "剪切", kb_paste: "粘贴",
    kb_delete: "删除", kb_rename: "重命名",
    kb_new_file: "新建文件", kb_new_dir: "新建文件夹",
    kb_search: "模糊搜索", kb_toggle_hidden: "切换隐藏文件",
    kb_new_tab: "新建标签", kb_close_tab: "关闭标签",
    kb_cycle_tab: "切换标签", kb_quit: "退出",
    kb_drives: "驱动器 / USB / 手机管理器",
    kb_header_nav: "── 导航 ─────────────────────────────────",
    kb_header_sel: "── 选择 ─────────────────────────────────",
    kb_header_ops: "── 文件操作 ──────────────────────────────",
    kb_header_tabs: "── 标签页 ───────────────────────────────",
    kb_header_drives: "── 驱动器和设备 ──────────────────────────",
    kb_header_app: "── 应用 ─────────────────────────────────",
    kb_nav_up: "向上", kb_nav_down: "向下",
    kb_nav_left: "返回", kb_nav_right: "打开 / 进入",
    kb_page_up: "上跳10", kb_page_down: "下跳10",
    kb_first: "第一项", kb_last: "最后一项",
    kb_navigate: "导航", kb_open: "打开 / 进入目录",
    kb_go_up: "向上", kb_jump: "跳转10条",
    kb_first_last: "第一条 / 最后一条",
    kb_deselect_all: "取消全选", kb_select_all2: "全选 (alt)",
    kb_open_with: "用…打开", kb_settings: "打开设置",
    kb_help: "显示帮助", kb_quit2: "退出 (alt)",
    kb_drive_mount: "挂载所选设备",
    kb_drive_unmount: "卸载所选设备",
    kb_drive_refresh: "刷新设备列表",
    kb_trash_open: "打开回收站",
    kb_edit_add_one: "添加一个按键",
    kb_edit_add_combo: "添加组合键  (如 Ctrl+K)",
    kb_edit_remove: "删除绑定",
    kb_edit_reset: "重置为默认",
    kb_edit_current: "当前",
    kb_edit_press_key: "按任意键 — 它将单独工作",
    kb_edit_step1: "按组合键的第一个键",
    kb_edit_step2: "第一个键: {} — 现在按第二个键",
    kb_edit_remove_title: "删除绑定",
    about_app: "应用", about_ver: "版本", about_author: "作者",
    about_license: "许可证", about_repo: "仓库",
    about_tagline: "梦幻虚空主题的TUI文件管理器",
    about_built_with: "基于 Rust + Ratatui 构建",
    help_navigation: "导航", help_file_ops: "文件操作",
    help_search: "搜索", help_tabs: "标签", help_app: "应用",
    help_move_cursor: "向上 / 向下移动光标",
    help_open_enter: "打开文件或进入目录",
    help_go_up: "返回上级目录",
    help_jump10: "跳转10条", help_first_last: "第一条 / 最后一条",
    help_select: "选择 / 取消选择文件",
    help_select_all: "全选", help_deselect_all: "取消全选",
    help_copy: "复制所选", help_cut: "剪切所选",
    help_paste: "粘贴", help_delete: "删除所选 (需确认)",
    help_rename: "重命名", help_new_file: "新建文件",
    help_new_dir: "新建文件夹", help_fuzzy: "模糊搜索 (递归)",
    help_new_tab: "打开新标签", help_close_tab: "关闭当前标签",
    help_cycle_tab: "切换到下一标签",
    help_toggle_hidden: "切换隐藏文件",
    help_drives: "打开驱动器 / USB / 手机管理器",
    help_drive_mount: "挂载所选驱动器或手机",
    help_drive_unmount: "卸载所选驱动器或手机",
    help_drive_refresh: "刷新设备列表",
    help_open_settings: "打开设置",
    help_show_help: "显示此帮助", help_quit: "退出",
    drive_title: "驱动器管理器",
    drive_no_devices: "未检测到可移动驱动器或手机。",
    drive_tip_plug: "插入USB驱动器或通过USB连接手机",
    drive_tip_mtp: "Android手机：请启用MTP模式",
    drive_tip_jmtpfs: "需要安装jmtpfs以支持手机",
    drive_col_name: "名称", drive_col_size: "大小",
    drive_col_fs: "文件系统", drive_col_mount: "挂载点",
    drive_hint_mount: "挂载", drive_hint_unmount: "卸载",
    drive_hint_navigate: "导航", drive_hint_refresh: "刷新",
    drive_hint_close: "关闭",
    msg_already_mounted: "已挂载 — 按 u 卸载",
    msg_cant_close_tab: "无法关闭最后一个标签",
    msg_cant_navigate: "无法导航到此分区类型",
    msg_not_mounted: "未挂载",
    msg_not_mounted_hint: "未挂载 — 请先按 m 挂载",
    msg_nothing_to_paste: "没有可粘贴的内容",
    msg_nothing_to_yank: "没有可复制的内容",
    msg_pasted: "粘贴成功",
    msg_select_first: "请先选择文件 (空格)",
    msg_hidden_shown: "已显示隐藏文件",
    msg_hidden_hidden: "已隐藏隐藏文件",
    msg_copied: "已复制", msg_cut: "已剪切",
    preview_folder_size: "文件夹大小", preview_items: "项",
    preview_item: "项", preview_computing: "…",
    msg_mounted_at: "已挂载到", msg_mount_failed: "挂载失败",
    msg_unmounted: "已卸载", msg_unmount_failed: "卸载失败",
    msg_extracted: "已解压", msg_extract_error: "解压错误",
    msg_deleted: "已删除", msg_deleted_items: "项",
    msg_error: "错误", msg_launching: "正在启动", msg_in_terminal: "在终端中",
    msg_tab_word: "标签", msg_opened_word: "已打开",
    msg_settings_saved: "设置已保存", msg_save_error: "保存错误",
    msg_unsaved_changes: "未保存的更改 — 按S保存",
    msg_extracting: "正在解压", msg_esc_cancel: "[Esc 取消]",
};

// ── Korean ────────────────────────────────────────────────────────────────────
static KO: Lang = Lang {
    sec_behaviour: "동작", sec_appearance: "외관",
    sec_openers: "열기 프로그램", sec_keybinds: "단축키", sec_about: "정보",
    set_show_hidden: "숨김 파일 표시", set_date_format: "날짜 형식",
    set_show_clock: "탭 바에 시계 표시", set_show_mtime: "파일 날짜/시간 표시",
    kb_select: "선택 / 선택 해제", kb_select_all: "모두 선택",
    kb_copy: "복사", kb_cut: "잘라내기", kb_paste: "붙여넣기",
    kb_delete: "삭제", kb_rename: "이름 바꾸기",
    kb_new_file: "새 파일", kb_new_dir: "새 폴더",
    kb_search: "퍼지 검색", kb_toggle_hidden: "숨김 파일 전환",
    kb_new_tab: "새 탭", kb_close_tab: "탭 닫기",
    kb_cycle_tab: "탭 전환", kb_quit: "종료",
    kb_drives: "드라이브 / USB / 전화 관리자",
    kb_header_nav: "── 탐색 ─────────────────────────────────",
    kb_header_sel: "── 선택 ─────────────────────────────────",
    kb_header_ops: "── 파일 작업 ────────────────────────────",
    kb_header_tabs: "── 탭 ───────────────────────────────────",
    kb_header_drives: "── 드라이브 및 장치 ──────────────────────",
    kb_header_app: "── 앱 ───────────────────────────────────",
    kb_nav_up: "위로", kb_nav_down: "아래로",
    kb_nav_left: "뒤로", kb_nav_right: "열기 / 들어가기",
    kb_page_up: "10 위로", kb_page_down: "10 아래로",
    kb_first: "첫 번째 항목", kb_last: "마지막 항목",
    kb_navigate: "탐색", kb_open: "열기 / 폴더 진입",
    kb_go_up: "위로", kb_jump: "10개 항목 이동",
    kb_first_last: "첫 번째 / 마지막 항목",
    kb_deselect_all: "모두 해제", kb_select_all2: "모두 선택 (alt)",
    kb_open_with: "다음으로 열기…", kb_settings: "설정 열기",
    kb_help: "도움말 표시", kb_quit2: "종료 (alt)",
    kb_drive_mount: "선택한 장치 마운트",
    kb_drive_unmount: "선택한 장치 마운트 해제",
    kb_drive_refresh: "장치 목록 새로 고침",
    kb_trash_open: "휴지통 열기",
    kb_edit_add_one: "키 하나 추가",
    kb_edit_add_combo: "조합 추가  (예: Ctrl+K)",
    kb_edit_remove: "바인딩 제거",
    kb_edit_reset: "기본값으로 재설정",
    kb_edit_current: "현재",
    kb_edit_press_key: "아무 키나 누르세요 — 단독으로 작동합니다",
    kb_edit_step1: "조합의 첫 번째 키를 누르세요",
    kb_edit_step2: "첫 번째 키: {} — 이제 두 번째 키를 누르세요",
    kb_edit_remove_title: "바인딩 제거",
    about_app: "응용 프로그램", about_ver: "버전", about_author: "작성자",
    about_license: "라이선스", about_repo: "저장소",
    about_tagline: "꿈같은 void 테마의 TUI 파일 관리자",
    about_built_with: "Rust + Ratatui로 제작",
    help_navigation: "탐색", help_file_ops: "파일 작업",
    help_search: "검색", help_tabs: "탭", help_app: "앱",
    help_move_cursor: "커서를 위 / 아래로 이동",
    help_open_enter: "파일 열기 또는 폴더 진입",
    help_go_up: "상위 폴더로 이동",
    help_jump10: "10개 항목 이동", help_first_last: "첫 번째 / 마지막 항목",
    help_select: "파일 선택 / 해제",
    help_select_all: "모두 선택", help_deselect_all: "모두 해제",
    help_copy: "선택 복사", help_cut: "선택 잘라내기",
    help_paste: "붙여넣기", help_delete: "선택 삭제 (확인 필요)",
    help_rename: "이름 바꾸기", help_new_file: "새 파일",
    help_new_dir: "새 폴더", help_fuzzy: "퍼지 검색 (재귀)",
    help_new_tab: "새 탭 열기", help_close_tab: "현재 탭 닫기",
    help_cycle_tab: "다음 탭으로",
    help_toggle_hidden: "숨김 파일 전환",
    help_drives: "드라이브 / USB / 전화 관리자 열기",
    help_drive_mount: "선택한 드라이브 또는 전화 마운트",
    help_drive_unmount: "선택한 드라이브 또는 전화 마운트 해제",
    help_drive_refresh: "장치 목록 새로 고침",
    help_open_settings: "설정 열기",
    help_show_help: "이 도움말 표시", help_quit: "종료",
    drive_title: "드라이브 관리자",
    drive_no_devices: "이동식 드라이브 또는 전화가 감지되지 않았습니다.",
    drive_tip_plug: "USB 드라이브를 꽂거나 USB로 전화를 연결하세요",
    drive_tip_mtp: "Android 전화: MTP 모드를 활성화하세요",
    drive_tip_jmtpfs: "전화 지원을 위해 jmtpfs가 설치되어야 합니다",
    drive_col_name: "이름", drive_col_size: "크기",
    drive_col_fs: "파일시스템", drive_col_mount: "마운트 지점",
    drive_hint_mount: "마운트", drive_hint_unmount: "마운트 해제",
    drive_hint_navigate: "탐색", drive_hint_refresh: "새로 고침",
    drive_hint_close: "닫기",
    msg_already_mounted: "이미 마운트됨 — u를 눌러 해제",
    msg_cant_close_tab: "마지막 탭은 닫을 수 없습니다",
    msg_cant_navigate: "이 파티션 유형으로 탐색할 수 없습니다",
    msg_not_mounted: "마운트되지 않음",
    msg_not_mounted_hint: "마운트되지 않음 — 먼저 m을 눌러 마운트하세요",
    msg_nothing_to_paste: "붙여넣을 내용 없음",
    msg_nothing_to_yank: "복사할 내용 없음",
    msg_pasted: "붙여넣기 완료",
    msg_select_first: "먼저 파일을 선택하세요 (스페이스)",
    msg_hidden_shown: "숨김 파일 표시됨",
    msg_hidden_hidden: "숨김 파일 숨겨짐",
    msg_copied: "복사됨", msg_cut: "잘라냄",
    preview_folder_size: "폴더 크기", preview_items: "항목",
    preview_item: "항목", preview_computing: "…",
    msg_mounted_at: "마운트 위치", msg_mount_failed: "마운트 실패",
    msg_unmounted: "마운트 해제됨", msg_unmount_failed: "마운트 해제 실패",
    msg_extracted: "압축 해제 완료", msg_extract_error: "압축 해제 오류",
    msg_deleted: "삭제됨", msg_deleted_items: "항목",
    msg_error: "오류", msg_launching: "실행 중", msg_in_terminal: "터미널에서",
    msg_tab_word: "탭", msg_opened_word: "열림",
    msg_settings_saved: "설정이 저장되었습니다", msg_save_error: "저장 오류",
    msg_unsaved_changes: "저장되지 않은 변경 사항 — S를 눌러 저장",
    msg_extracting: "압축 해제 중", msg_esc_cancel: "[Esc 취소]",
};

// ── Arabic ────────────────────────────────────────────────────────────────────
static AR: Lang = Lang {
    sec_behaviour: "السلوك", sec_appearance: "المظهر",
    sec_openers: "البرامج الافتراضية", sec_keybinds: "اختصارات", sec_about: "حول",
    set_show_hidden: "إظهار الملفات المخفية", set_date_format: "تنسيق التاريخ",
    set_show_clock: "إظهار الساعة في شريط التبويبات",
    set_show_mtime: "إظهار تاريخ/وقت الملف",
    kb_select: "تحديد / إلغاء التحديد", kb_select_all: "تحديد الكل",
    kb_copy: "نسخ", kb_cut: "قص", kb_paste: "لصق",
    kb_delete: "حذف", kb_rename: "إعادة التسمية",
    kb_new_file: "ملف جديد", kb_new_dir: "مجلد جديد",
    kb_search: "بحث ضبابي", kb_toggle_hidden: "تبديل الملفات المخفية",
    kb_new_tab: "تبويب جديد", kb_close_tab: "إغلاق التبويب",
    kb_cycle_tab: "التنقل بين التبويبات", kb_quit: "خروج",
    kb_drives: "مدير الأقراص / USB / الهاتف",
    kb_header_nav: "── تنقل ─────────────────────────────────",
    kb_header_sel: "── تحديد ────────────────────────────────",
    kb_header_ops: "── عمليات الملفات ───────────────────────",
    kb_header_tabs: "── تبويبات ──────────────────────────────",
    kb_header_drives: "── الأقراص والأجهزة ──────────────────────",
    kb_header_app: "── التطبيق ──────────────────────────────",
    kb_nav_up: "أعلى", kb_nav_down: "أسفل",
    kb_nav_left: "رجوع", kb_nav_right: "فتح / دخول",
    kb_page_up: "قفز 10 أعلى", kb_page_down: "قفز 10 أسفل",
    kb_first: "أول إدخال", kb_last: "آخر إدخال",
    kb_navigate: "تصفح", kb_open: "فتح / الدخول إلى المجلد",
    kb_go_up: "للأعلى", kb_jump: "قفز 10 إدخالات",
    kb_first_last: "الأول / الأخير",
    kb_deselect_all: "إلغاء تحديد الكل", kb_select_all2: "تحديد الكل (بديل)",
    kb_open_with: "فتح بواسطة…", kb_settings: "فتح الإعدادات",
    kb_help: "عرض المساعدة", kb_quit2: "خروج (بديل)",
    kb_drive_mount: "تركيب الجهاز المحدد",
    kb_drive_unmount: "إلغاء تركيب الجهاز المحدد",
    kb_drive_refresh: "تحديث قائمة الأجهزة",
    kb_trash_open: "فتح سلة المهملات",
    kb_edit_add_one: "إضافة مفتاح واحد",
    kb_edit_add_combo: "إضافة مجموعة  (مثل Ctrl+K)",
    kb_edit_remove: "حذف ربط",
    kb_edit_reset: "إعادة الضبط الافتراضي",
    kb_edit_current: "الحالي",
    kb_edit_press_key: "اضغط أي مفتاح — سيعمل بمفرده",
    kb_edit_step1: "اضغط المفتاح الأول للمجموعة",
    kb_edit_step2: "المفتاح الأول: {} — اضغط الآن المفتاح الثاني",
    kb_edit_remove_title: "حذف الربط",
    about_app: "التطبيق", about_ver: "الإصدار", about_author: "المؤلف",
    about_license: "الترخيص", about_repo: "المستودع",
    about_tagline: "مدير ملفات TUI بتصميم void حالم",
    about_built_with: "مبني بـ Rust + Ratatui",
    help_navigation: "التنقل", help_file_ops: "عمليات الملفات",
    help_search: "بحث", help_tabs: "تبويبات", help_app: "التطبيق",
    help_move_cursor: "تحريك المؤشر لأعلى / لأسفل",
    help_open_enter: "فتح ملف أو الدخول إلى مجلد",
    help_go_up: "الانتقال إلى المجلد الأصلي",
    help_jump10: "قفز 10 إدخالات", help_first_last: "الأول / الأخير",
    help_select: "تحديد / إلغاء تحديد ملف",
    help_select_all: "تحديد الكل", help_deselect_all: "إلغاء تحديد الكل",
    help_copy: "نسخ المحدد", help_cut: "قص المحدد",
    help_paste: "لصق", help_delete: "حذف المحدد (مع تأكيد)",
    help_rename: "إعادة التسمية", help_new_file: "ملف جديد",
    help_new_dir: "مجلد جديد", help_fuzzy: "بحث ضبابي (تكراري)",
    help_new_tab: "فتح تبويب جديد", help_close_tab: "إغلاق التبويب الحالي",
    help_cycle_tab: "الانتقال إلى التبويب التالي",
    help_toggle_hidden: "تبديل الملفات المخفية",
    help_drives: "فتح مدير الأقراص / USB / الهاتف",
    help_drive_mount: "تركيب القرص أو الهاتف المحدد",
    help_drive_unmount: "إلغاء تركيب القرص أو الهاتف المحدد",
    help_drive_refresh: "تحديث قائمة الأجهزة",
    help_open_settings: "فتح الإعدادات",
    help_show_help: "عرض هذه المساعدة", help_quit: "خروج",
    drive_title: "مدير الأقراص",
    drive_no_devices: "لم يتم اكتشاف أقراص قابلة للإزالة أو هواتف.",
    drive_tip_plug: "أدخل USB أو قم بتوصيل الهاتف عبر USB",
    drive_tip_mtp: "للهواتف Android: قم بتفعيل وضع MTP",
    drive_tip_jmtpfs: "يجب تثبيت jmtpfs لدعم الهاتف",
    drive_col_name: "الاسم", drive_col_size: "الحجم",
    drive_col_fs: "نظام الملفات", drive_col_mount: "نقطة التركيب",
    drive_hint_mount: "تركيب", drive_hint_unmount: "إلغاء التركيب",
    drive_hint_navigate: "تصفح", drive_hint_refresh: "تحديث",
    drive_hint_close: "إغلاق",
    msg_already_mounted: "مركب بالفعل — اضغط u للإلغاء",
    msg_cant_close_tab: "لا يمكن إغلاق آخر تبويب",
    msg_cant_navigate: "لا يمكن التنقل في هذا النوع من الأقسام",
    msg_not_mounted: "غير مركب",
    msg_not_mounted_hint: "غير مركب — اضغط m للتركيب أولاً",
    msg_nothing_to_paste: "لا يوجد شيء للصق",
    msg_nothing_to_yank: "لا يوجد شيء للنسخ",
    msg_pasted: "تم اللصق بنجاح",
    msg_select_first: "حدد الملفات أولاً (مسافة)",
    msg_hidden_shown: "الملفات المخفية مرئية",
    msg_hidden_hidden: "الملفات المخفية مخفية",
    msg_copied: "تم النسخ", msg_cut: "تم القص",
    preview_folder_size: "حجم المجلد", preview_items: "عناصر",
    preview_item: "عنصر", preview_computing: "…",
    msg_mounted_at: "تم التركيب في", msg_mount_failed: "فشل التركيب",
    msg_unmounted: "تم إلغاء التركيب", msg_unmount_failed: "فشل إلغاء التركيب",
    msg_extracted: "تم الاستخراج", msg_extract_error: "خطأ في الاستخراج",
    msg_deleted: "تم الحذف", msg_deleted_items: "عنصر",
    msg_error: "خطأ", msg_launching: "تشغيل", msg_in_terminal: "في الطرفية",
    msg_tab_word: "تبويب", msg_opened_word: "مفتوح",
    msg_settings_saved: "تم حفظ الإعدادات", msg_save_error: "خطأ في الحفظ",
    msg_unsaved_changes: "تغييرات غير محفوظة — اضغط S للحفظ",
    msg_extracting: "جارٍ الاستخراج", msg_esc_cancel: "[Esc إلغاء]",
};
